version: '3.8'

services:
  server:
    image: city-bikes-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    container_name: server
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    volumes:
      - dev_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dev_data: